# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update positive parameters in the no-regression case
#' @param type 0 or 1: updates mu, or nu
#' @param params c(mu, nu) vector
#' @param y data
#' @param sigma c(sigma_mu, sigma_nu) vector of proposal parameters
#' @param shape c(shape_mu, shape_nu) Gamma prior shape parameters
#' @param rate c(rate_mu, rate_nu) Gamma prior rate parameters
update_positive <- function(type, params, y, sigma, shape, rate) {
    .Call(`_cpbayes_update_positive`, type, params, y, sigma, shape, rate)
}

#' MCMC sampling: no regression case
#' @param y data
#' @param params0 initial parameter values
#' @param sigma c(sigma_mu, sigma_nu) vector of proposal parameters
#' @param n_iter number of iterations to store
#' @param burn_in burn-in period
#' @param hyperparams named list containing 'shape' c(shape_mu, shape_nu) gamma prior shape parameters and
#' 'rate' c(rate_mu, rate_nu) Gamma prior rate parameters.
exchange_noreg <- function(y, params0, sigma, n_iter, burn_in, hyperparams) {
    .Call(`_cpbayes_exchange_noreg`, y, params0, sigma, n_iter, burn_in, hyperparams)
}

#' COM-Poisson rejection sampling
#'
#' @param n number of samples
#' @param mu location parameter
#' @param nu dispersion parameter
#' @output integer vector
rcompois <- function(n, mu, nu) {
    .Call(`_cpbayes_rcompois`, n, mu, nu)
}

