# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' COM-Poisson rejection sampling
#'
#' @param n number of samples
#' @param mu location parameter
#' @param nu dispersion parameter
#' @output integer vector
rcompois <- function(n, mu, nu) {
    .Call(`_cpbayes_rcompois`, n, mu, nu)
}

